env:
  es6: true
  browser: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
overrides:
  - { files: ['*.test.js'], env: { jest: true } }
rules: {}
